name: Robert West
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100e0f'
    - '#a4a198'
    - '#df4312'
    - '#443f3c'
    - '#4078a3'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
