name: Robert West
favicon: null
layout_spectrum: 0.2579
typography_spectrum: 0.8207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c3c2bd'
    - '#060606'
    - '#f9432a'
    - '#489284'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
